plugins {
    id 'com.android.library'
}

android {
    compileSdk 34

    defaultConfig {
        minSdk 16
        targetSdk 28
    }

    lint {
        disable 'UnsafeOptInUsageError'
    }
}

dependencies {
    implementation project(':catvod')
    //implementation(ext: 'aar', name: 'lib-ui-release', group: 'fongmi', version: 'release')
    //implementation(ext: 'aar', name: 'lib-common-release', group: 'fongmi', version: 'release')
    // ✨✨✨ 就是在这里！给 ijkplayer 输血！ ✨✨✨
    implementation 'com.google.android.exoplayer:exoplayer-ui:2.14.2'
}
